apiVersion: apps/v1
kind: Deployment
metadata:
  name: cpu-cores-max-procs
  labels:
    app: cpu-cores-max-procs
spec:
  selector:
    matchLabels:
      app: cpu-cores-max-procs
  template:
    metadata:
      labels:
        app: cpu-cores-max-procs
    spec:
      containers:
      - name: cpu-cores-max-procs
        image: cpu-cores-image
        ports:
          - name: http
            containerPort: 8009
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "2"
---
apiVersion: v1
kind: Service
metadata:
  name: cpu-cores-max-proces-svc
  annotations:
    prometheus.io/scrape: 'true'
spec:
  selector:
    name: cpu-cores-max-procs
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8009
